package com.umlgenerator.core.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

/**
 * Represents a complete relational schema (collection of tables).
 * Generated from ER/EERD diagrams via relational mapping algorithm.
 */
public class RelationalSchema {
    private String title;
    private List<RelationalTable> tables;

    public RelationalSchema() {
        this.tables = new ArrayList<>();
    }

    public RelationalSchema(String title) {
        this();
        this.title = title;
    }

    // Getters and setters
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public List<RelationalTable> getTables() { return tables; }
    public void setTables(List<RelationalTable> tables) { this.tables = tables; }
    public void addTable(RelationalTable table) { this.tables.add(table); }

    /**
     * Find a table by name.
     */
    public Optional<RelationalTable> findTable(String name) {
        return tables.stream().filter(t -> t.getName().equalsIgnoreCase(name)).findFirst();
    }

    /**
     * Generate complete SQL DDL script.
     */
    public String toSQL() {
        StringBuilder sb = new StringBuilder();
        sb.append("-- Relational Schema: ").append(title).append("\n");
        sb.append("-- Generated by UML Generator Pro\n");
        sb.append("-- Tables: ").append(tables.size()).append("\n\n");

        for (RelationalTable table : tables) {
            sb.append(table.toSQL()).append("\n\n");
        }
        return sb.toString();
    }

    /**
     * Generate relational mapping notation.
     * Each table shown as: TableName(PK:id, col1, FK:ref_id)
     */
    public String toMappingNotation() {
        return tables.stream()
                .map(RelationalTable::toMappingString)
                .collect(Collectors.joining("\n"));
    }

    @Override
    public String toString() {
        return "RelationalSchema{" + title + ", tables=" + tables.size() + "}";
    }
}
